import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {NuqsAdapter} from "nuqs/adapters/next/app";
import "./globals.css";
import "@liveblocks/react-ui/styles.css";
import "@liveblocks/react-tiptap/styles.css";
import {ConvexClientProvider} from '@/components/ui/convex-client-provider'
import {Toaster} from "@/components/ui/sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
			<html lang='en'>
				<body
					suppressHydrationWarning
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<NuqsAdapter>
						<ConvexClientProvider>
							<Toaster />
							{children}
						</ConvexClientProvider>
					</NuqsAdapter>
				</body>
			</html>
		);
}
